### ISSUE TITLE
能否根据国内情况修改源？

### ISSUE THREAD

**Issue by LHM-0** [jeffok/tunasync#1]
![Snipaste_2024-06-16_19-30-23](https://github.com/jeffok/tunasync/assets/58819222/8184bab7-e256-4f6a-ba9f-87376b925173)
大哥，我用阿里docker源解决了前一个错误，现在又来一个，怎么整？

**Comment by jeffok** [comment]
你可以直接使用Docker，不需要编译
docker push jeffok/tunasync:tagname
